name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: docker build . --tag ghcr.io/home-assistant/amd64-addon-example:latest
      - name: Run the Docker image
          docker run ghcr.io/home-assistant/amd64-addon-example:latest
      - name: Push the Docker image
          docker push ghcr.io/home-assistant/amd64-addon-example:latest